// Copyright 2023 Smirnov Pavel
#ifndef MODULES_TASK_1_SMIRNOV_P_MOST_DIFFERENT_VECTOR_ELEMENTS_MOST_DIFFERENT_VECTOR_ELEMENTS_H_
#define MODULES_TASK_1_SMIRNOV_P_MOST_DIFFERENT_VECTOR_ELEMENTS_MOST_DIFFERENT_VECTOR_ELEMENTS_H_


#include <vector>

using namespace std;

vector<int> getRandVect(int n);
int single_find(vector<int> v);
int mpi_find(vector<int> v);

#endif  // MODULES_TASK_1_SMIRNOV_P_MOST_DIFFERENT_VECTOR_ELEMENTS_MOST_DIFFERENT_VECTOR_ELEMENTS_H_
